project:
  type: website
  output-dir: docs
  author: "Daoming Liu"

website:
  title: "Construction in Progress"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



